# Generated by Django 5.2.8 on 2025-12-03 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispatch', '0003_alter_ambulance_current_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatcherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('shift_schedule', models.CharField(blank=True, max_length=100)),
                ('certifications', models.TextField(blank=True, help_text='List of relevant certifications')),
                ('experience_years', models.IntegerField(default=0)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispatcher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispatcher Profile',
                'verbose_name_plural': 'Dispatcher Profiles',
            },
        ),
        migrations.CreateModel(
            name='ParamedicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('certifications', models.TextField(blank=True, help_text='List of medical certifications')),
                ('specialties', models.TextField(blank=True, help_text='Medical specialties')),
                ('experience_years', models.IntegerField(default=0)),
                ('shift_schedule', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_ambulance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dispatch.ambulance')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paramedic_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paramedic Profile',
                'verbose_name_plural': 'Paramedic Profiles',
            },
        ),
    ]
